language: go
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

go:
  - 1.x

before_install:
  - go get -v github.com/golang/lint/golint

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - go vet ./...
  - $GOPATH/bin/golint .
  - go test -cpu=2 -v ./...
