language: go
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

go:
  - 1.7

before_install:
  - go get -v github.com/golang/lint/golint

install:
  - go install -race -v std
  - go get -race -t -v ./...
  - go install -race -v ./...

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - go vet ./...
  - $HOME/gopath/bin/golint .
  - go test -cpu=2 -race -v ./...
  - go test -cpu=2 -covermode=atomic ./...
